# Docker Compose configuration for FloppFun
version: '3.8'

services:
  # Vue.js frontend application
  pump-fun-clone:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:80"
    environment:
      # Supabase configuration
      - VITE_SUPABASE_URL=https://mlczuanztnqcngioayas.supabase.co
      - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sY3p1YW56dG5xY25naW9heWFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NzIwOTYsImV4cCI6MjA2MjM0ODA5Nn0.ShPAiWshDqZD0pAP9RMGdpfrpBtoGd58r_agzigReeI
      
      # Solana configuration
      - VITE_SOLANA_RPC_URL=https://api.devnet.solana.com
      - VITE_SOLANA_NETWORK=devnet
      
      # Application configuration
      - VITE_APP_NAME=FloppFun
      - VITE_APP_VERSION=1.0.0
    
    volumes:
      # Mount nginx logs for debugging
      - nginx-logs:/var/log/nginx
    
    restart: unless-stopped
    
    networks:
      - pump-fun-network
    
    # Health check to ensure service is running
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (uncomment for development)
  # pump-fun-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: build
  #   ports:
  #     - "3001:3000"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   command: npm run dev
  #   networks:
  #     - pump-fun-network

# Named volumes for data persistence
volumes:
  nginx-logs:
    driver: local

# Custom network for service communication
networks:
  pump-fun-network:
    driver: bridge 